name: Check in

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Run check-in
        env:
          SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
          SMZDM_SK: ${{ secrets.SK }}
          SMZDM_PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          SMZDM_SC_KEY: ${{ secrets.SC_KEY }}
          SMZDM_TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          SMZDM_TG_USER_ID: ${{ secrets.TG_USER_ID }}
          SMZDM_TG_API_BASE: ${{ secrets.TG_BOT_API }}
        run: |
          smzdm-bot run
